services:
  backend:
    build:
      context: ./demo-backend
    container_name: devops-demo-backend
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./demo-frontend
    container_name: devops-demo-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend